name: vectorenv19
channels:
- conda-forge
- default
dependencies:
- python=3.7
- geopandas=0.5.1
- psycopg2
- geojson
- pysal
- mapclassify
- pyepsg
- utm
- rasterstats
- requests
- folium
- seaborn
- geoviews
- osmnx
- jupyter
